
version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - '4444:4444'
  client:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    links:
      - 'api'